development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  url: postgres://ndxycxyucsibqs:0ab6499cafca6b8a8a05a9b85c0c0128126bba63905d7f99d35f183bfa7a17c3@ec2-23-21-220-48.compute-1.amazonaws.com:5432/d6oku4g94b2j8j
  channel_prefix: testapp_production


#production:
 # adapter: redis
  #url: redis://localhost:6379/1
  #channel_prefix: test_app_production
